//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBS.DataAccessLayer.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public int Id { get; set; }
        public int CustomerId { get; set; }
        public int DealerId { get; set; }
        public int MechanicId { get; set; }
        public int VehicleId { get; set; }
        public System.DateTime AppointmentDate { get; set; }
        public int ServiceId { get; set; }
        public int Status { get; set; }
        public int UpdatedBy { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
