//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACS.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vehicle()
        {
            this.ServiceBookings = new HashSet<ServiceBooking>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string NumberPlate { get; set; }
        public string ChassisNumber { get; set; }
        public System.DateTime RegistrationDate { get; set; }
        public Nullable<System.DateTime> LastServiceDate { get; set; }
        public string FuelType { get; set; }
        public int CustomerId { get; set; }
        public int ModelId { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Model Model { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceBooking> ServiceBookings { get; set; }
    }
}
